apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: external-secret
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
          - name: TEST_STR
            valueFrom:
              secretKeyRef:
                name: my-secret-str
                key: mysql_connection_string
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-volume"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret-file