---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: secret-str
    namespace: external-secret
spec:
    refreshInterval: 1m
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: my-secret-str
        creationPolicy: Owner
        deletionPolicy: Delete
    data:
        - secretKey: mysql_connection_string
          remoteRef:
            key: name:Test_secret_str