---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: secret-file
    namespace: external-secret
spec:
    refreshInterval: 1m
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: my-secret-file
        creationPolicy: Owner
        deletionPolicy: Delete
    data:
        - secretKey: secret.json
          remoteRef:
            key: name:Test_secret_obj
        