---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: secret-api
    namespace: external-secret
spec:
    refreshInterval: 1m
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: my-secret-api
        creationPolicy: Owner
        deletionPolicy: Delete
    dataFrom:
        - extract:
            key: name:Test_secret_obj
        