---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: external-secret
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: f061755e-7d42-48c1-9579-0ad4084eea14
      accessKey:
        secretRef:
          name: secret-manager-secret
          key: access-key
      secretKey:
        secretRef:
          name: secret-manager-secret
          key: secret-access-key